CREATE TABLE IF NOT EXISTS TRAINING (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

INSERT INTO TRAINING (name, category) VALUES ('kotlin', 'PROGRAMACAO');
INSERT INTO USERS (name, email) VALUES ('user test', 'email@email.com');