name: PIPELINE-CD

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml')}}
          restore-keys: ${{ runner.os }}-m2

      - name: Clean Package
        run: mvn clean

      - name: Create package
        run: mvn package

      - name: Login container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Push container registry
        env:
          HEROKU_API_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: heroku container:push -a${{secrets.HEROKU_APP_NAME }}

      - name: Release container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a${{secrets.HEROKU_APP_NAME }} web